name: Deploy Static Website to GitHub Pages

on:
  push:
    branches: [ "main" ]    # runs when you push to main

permissions:
  contents: read
  pages: write              # permission to deploy to pages
  id-token: write           # permission to verify deployment

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}   # live URL

    steps:

      # Step 1 - Download your code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2 - Setup GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Step 3 - Upload your website files
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'         # uploads everything in root folder

      # Step 4 - Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
